### ISSUE TITLE
Black Trout bait needs a change

### ISSUE THREAD

**Issue by tjdwo13579** [Vicen04/Dw1DataAndPatches#1]
According to the Text file Black trout likes
SpinyGreen / Big Berry / Prickly Pear / Power Fruit / Power Ice / Sage Fruit / Speed Leaf / Muscle Yam / Calm Berry

All of these are rare overworld items, so getting a reliable bait for Black trout is quite frustrating
I'm pretty sure in the original, Digimushroom was one of it's baits.
So it's quite reliable to fish Black trout -> Ultimately used for Digiseabass bait.

I suggest adding a bait that's reasonable to acquire, maybe one of the smaller fishes could be bait or Digimushroom (like the original)

Also could you check if big berry is coded as it's baits?? I'm pretty sure I tried it with a big berry but it didn't bite (showing X)

**Comment by Vicen04** [comment]
Hi,

I do apologise, but this is probably about the "Maeson" version, since I'm not the author, I'm unable to do changes to it; that version just uses my bug fixes and some extra changes to add extra digimon and fix the evolution, changes to add the evolution items, tournament, lifetime, some information to be able to change some other data  and factorial town I did. 
This is not one of them, since the changes to fishing in that hack is not code, just script. A list of the changes made by me should be inside the "extra" folder I believe...

This is also not really mentioned in the Maeson Readme (or maybe I have not seen it), but the digimon that drop the Power Fruit / Power Ice / Sage Fruit / Speed Leaf / Muscle Yam / Calm Berry have a higher chance to drop them. 
The fishes that attract the other ones still work too (since it was not a code change and that's part of the code), so if you use a Digifishcat to attract the Digiseabass, it can be use to move them to the shore. Same with the Black trout and the Digitrout as bait.

I did check that version just in case, and it is true that the Big Berry is not working as bait, I'll send him a message about it. And maybe to put back some of the fish as bait if possible...

To answer about the original, I'm pretty sure the Digimushroom was not a bait for the Black trout, here's a list of bait from the original made by SydMontague:
https://docs.google.com/spreadsheets/d/19E7zgE2JJN4LQnlv9TNzenTaeld5OcRzC99EkiM80Cw/edit#gid=1580562331

Again, I apologise for any confusion caused, I'm just unable to change that hack.

**Comment by tjdwo13579** [comment]
Also I want to make note that Black trout is one the ingredients for recruiting mojyamon.
So adding an easier bait for black trout is quite crucial for progress of the game

**Comment by Vicen04** [comment]
Hi,

I'm glad you're enjoying the hack. I would recommend to defeat a few ice devimon in freeze land, that should give you a speed leaf. 
Or if you're having too many difficulties, you can always use the save data with either the original version or my version, the save data should be compatible (unless you're using by any chance the secret digimon). 

He's now aware of this issue and will have a look later. If you have an account at romhacking, you should be able to contact him and also write a review which helps. 

I believe he also has a github account, but since his hack only changes the script, there's no code involved. So I'm sure there's not really a repository for it.

If you find any mayor bug, you're welcome to let me know.
