### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Em4nu3lV1ct0r** [Vicen04/Dw1DataAndPatches#13]
Would it be possible to reconstruct Weregarurumon with the Leomon/Panjyamon skeleton and Garurumon's skin?

Or maybe importing the Weregarurumon skin from DW2 and covering Leomon's skeleton? (that shouldn't even be possible haha)

![WereGarurumon-Front.jpg](https://github.com/user-attachments/assets/f77ef1c0-0d2e-4862-b129-eef5c0b1ebc2)

![Leomon-Front.jpg](https://github.com/user-attachments/assets/a555ac23-92c2-4201-9618-8a221f2b9392)

![Garurumon-Front.jpg](https://github.com/user-attachments/assets/c3b88fb5-4408-4b9f-98ef-b2561f3aa9f1)

![Picsart_24-09-15_00-21-54-684.jpg](https://github.com/user-attachments/assets/944fd245-e7ee-49c9-b168-c4168d811c1e)

Checking Digimon World 2, I noticed that Leomon(visually identical in DW1 and DW2) and Weregarurumon's body model are the same, the only real changes are the colors and head.

The head must be the biggest challenge, but if something of this level were possible, the mod would be legendary, the repercussion on the internet would be insane haha.

Maybe you've already thought about it but discarded the idea because it was impossible, but it wouldn't hurt to bring the idea here hehe.

Another crazy idea: increase the size of Tyranomon's skeleton (I don't know if this is possible either) and apply the matertyranomon skin, to create a fully functional MasterTyranomon, since the original is unplayable because all animations are missing.

Or just change Tyranomon's color, add new Skills, boom: new Ultimate in DW1.

![IMG_20240915_003445.jpg](https://github.com/user-attachments/assets/160a3ead-d62d-428c-a974-237b328a7232)

**Comment by Vicen04** [comment]
You are not the first one that has the idea of just using a Garurumon head with Leomon's model. It still would require to redo the animations (ignoring the part of the model creation and that it would require not only a new texture, but to set the model to read the texture).  You are also ignoring the fact that WereGarurumon does not have a tail... (well it actually does in the official artwork, a wolf one, but modelling one would be a different issue).

So WereGarurumon would basically need a brand new model, a brand new texture and new animations (or at least heavily modify the Leomon one, it would be basically making a new one anyway). 
Now I do actually have made a WereGarurumon model (untextured) and the first basic animation, but it required a huge amount of work for it to be done.

It needs a proper texture and the model lacks a way to properly read the a new texture and... animations...

A bigger Tyrannomon would require brand new animation data, due to how the animations work in the game. Swapping the skin is not an issue, but that can be done for any digimon.
If you only want a texture change, you can try this tutorial: [Digimon texture change tutorial](https://github.com/Vicen04/Dw1DataAndPatches/wiki/Make-something-similar-to-the-Vermillimon-patch)

Now on top of what I mentioned, the game does not have room for new models/animations. You either remove one of the existing models with a size that fits (the only candidates would be playable digimon) or basically remake the entire code to add more. You would also need to expand the data that is read to raise and handle the digimon.

**Comment by Em4nu3lV1ct0r** [comment]
I understand, working with this game must be much more difficult than with a current game.

The Skills part really interested me, but I still haven't gotten a good result.

Is it very difficult, for example, to put an Ice Statue on Machinedramon with your Animation for Megalo spark?

I have some Skills ideas using his existing animation base, but I haven't gotten any results yet (I'm just curious about Programming haha).

It would be really cool if you brought to your channel a tutorial on how you made some changes, like the one with Skills, of course depending on your time, willingness, and if the change is something simpler.

**Comment by Em4nu3lV1ct0r** [comment]
> You are not the first one that has the idea of just using a Garurumon head with Leomon's model. It still would require to redo the animations (ignoring the part of the model creation and that it would require not only a new texture, but to set the model to read the texture).  You are also ignoring the fact that WereGarurumon does not have a tail... (well it actually does in the official artwork, a wolf one, but modelling one would be a different issue).
> 
> So WereGarurumon would basically need a brand new model, a brand new texture and new animations (or at least heavily modify the Leomon one, it would be basically making a new one anyway). 
> Now I do actually have made a WereGarurumon model (untextured) and the first basic animation, but it required a huge amount of work for it to be done.
> 
> It needs a proper texture and the model lacks a way to properly read the a new texture and... animations...
> 
> A bigger Tyrannomon would require brand new animation data, due to how the animations work in the game. Swapping the skin is not an issue, but that can be done for any digimon.
> If you only want a texture change, you can try this tutorial: [Digimon texture change tutorial](https://github.com/Vicen04/Dw1DataAndPatches/wiki/Make-something-similar-to-the-Vermillimon-patch)
> 
> Now on top of what I mentioned, the game does not have room for new models/animations. You either remove one of the existing models with a size that fits (the only candidates would be playable digimon) or basically remake the entire code to add more. You would also need to expand the data that is read to raise and handle the digimon.

I understand, working with this game must be much more difficult than with a current game.

The Skills part really interested me, but I still haven't gotten a good result.

Is it very difficult, for example, to put an Ice Statue on Machinedramon with your Animation for Megalo spark?

I have some Skills ideas using his existing animation base, but I haven't gotten any results yet (I'm just curious about Programming haha).

It would be really cool if you brought to your channel a tutorial on how you made some changes, like the one with Skills, of course depending on your time, willingness, and if the change is something simpler.

**Comment by Vicen04** [comment]
The wiki has plenty of data and most of the offsets can be found either there or in the TXT inside the "other data" folder.
A lot of the changes you are suggesting do not require code knowledge.

The only things you need is a hex editor and to learn a bit how it works. Then just learn and understand a bit about the game, no code knowledge required. There is plenty of information about it.

**Comment by Em4nu3lV1ct0r** [comment]
> The wiki has plenty of data and most of the offsets can be found either there or in the TXT inside the "other data" folder.
> A lot of the changes you are suggesting do not require code knowledge.
> 
> The only things you need is a hex editor and to learn a bit how it works. Then just learn and understand a bit about the game, no code knowledge required. There is plenty of information about it.


Good, the changes I think are based on things you have already done, in that I see that they are possible (most of them)


I'll close the topic, thanks man.
