### ISSUE TITLE
Little Avance 

### ISSUE THREAD

**Issue by Em4nu3lV1ct0r** [Vicen04/Dw1DataAndPatches#14]
I was able to apply this small change by following the tutorials, Machinedramon with Ice Statue haha, there are still adjustments to the location, distance and time of execution,  but the result was cool.

Unfortunately the skill removed had to be Megalo spark, I still don't understand the animation and skill link, my goal was to remove the Counter skill.

I wanted to show why you might think it's cool and want to implement it in the mod 😅.

https://github.com/user-attachments/assets/03a610a1-8bf4-4200-8cdb-43ca9028b349

**Comment by Vicen04** [comment]
I'll give you a little help since you have managed to progress that far:

I have explained that in the animations txt, but if you go to the animations offset for Machinedramon, you will come with multiple values, you want to go there and select a lenght of B8:

![image](https://github.com/user-attachments/assets/7aff3873-ce57-4f7e-84ff-50775e90fdda)


All of the animations after that are the techniques animations, it follows the order in the digimon data: 

![image](https://github.com/user-attachments/assets/1a0dd3ae-a15b-4b3b-a049-54cdbf39e684)

The first one would be Megaton Punch, the second Megalo Spark... and so on until the last tech. Just remember that the limit is set by the first value in that offset:

![image](https://github.com/user-attachments/assets/6101bcd7-e37d-420d-92bd-36c2e6b89d62)


Now, here I'm going to highlight the animation pointer for Megalo Spark and the one for counter:

![Animations help](https://github.com/user-attachments/assets/92112059-1b41-45d6-83aa-5245ac5780da)

_Counter in purple, Megalo Spark in Yellow_


To modify the animation it will play, you only have to copy the value of **Megalo Spark** and use it for the animation of **Counter**:

![image](https://github.com/user-attachments/assets/a1803325-004a-42a6-8cc5-27560a25159d)


Now, the reason why I did not give **Ice Statue** to Machinedramon: It is pretty big, if I make the tech activate from the tip of the arm (as it should be) it misses a lot. The animation is also a bit slower than the actual technique...

The timing of the activation of a technique is based on the technique itself, it has nothing to do with the digimon.

**Comment by Em4nu3lV1ct0r** [comment]
I see, I thought it was something adjustable, Ice Statue really makes a lot of mistakes, I'll try these modifications and see what happens.

I'll close the topic, thanks man.
