### ISSUE TITLE
Grey Lord Mansion refuses entry with key in inventory

### ISSUE THREAD

**Issue by paulo27ms** [Vicen04/Dw1DataAndPatches#19]
I didn't test with a virus type so don't know if it's completely bugged. I was allowed in without a virus type then I got a key and couldn't enter again. Using the patch installer on the release page.

**Comment by Vicen04** [comment]
Vice hack or the optional patch in the hardcore/optional section?

**Comment by paulo27ms** [comment]
It's Maseon's hack. I tried the standalone file from the releases here from Feb 28th (well, it seems the same as the one included in the Maseon one, based on the file size) and also doesn't work (on top of his patch).

**Comment by Vicen04** [comment]
Okay, I did compare it to the Vice hack and it seems that the check is done in an inverted way in the Mansion:
It checks if you have the Key, then blocks you if you have it, rather than letting you enter.
It also ignores the first check which is the type one.
I just updated the standalone in the Github, I'll update the installer later

**Comment by paulo27ms** [comment]
Just tested and it seems good, thanks!
