### ISSUE TITLE
[Suggestion/Request] Arena Menu Glitches

### ISSUE THREAD

**Issue by AlanBTG** [Vicen04/Dw1DataAndPatches#2]
Since you fixed some of the menu bugs I wanted to suggest taking a look at the Arena glitches listed in this gamefaq

https://gamefaqs.gamespot.com/ps/913684-digimon-world/faqs/45832

Mainly the signup screen showing the wrong available tournaments.

Anyways, thank you so much for making all these patches.

**Comment by Vicen04** [comment]
I'll have a look this weekend, but it will depend on how busy I am.

**Comment by Vicen04** [comment]
Hi,

I made a patch for it, but I would recommend to just download the new version of the hack and apply it since it has a few new features/ patches too.

If you're happy with the fix, please close the issue, otherwise, just post a message here with any issues you may have found.

As some extra trivia, the "arena error 1" shown in the link is not really that much of an error, the cup is actually named in the files "Thunder Wind".
